language: node_js
sudo: false
node_js: 8.8.0
cache:
  directories:
    - node_modules
install: npm install
stages:
  - name: functional-test
  - name: deploy
    # if: branch = master
jobs:
  include:
    - stage: functional-test
      script: npm start & (wait-on http://localhost:3000 && cypress run)
    - stage: deploy 
      script: ./ci/deploy
      deploy: &heroku
        provider: heroku
        app: $HEROKU_APP_NAME
        api_key:
          secure: "$HEROKU_KEY"