language: node_js
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
stages:
  - name: functional-test
  - name: deploy
    if: branch = master
  - name: smoke-test
    if: branch = master
jobs:
  include:
    - stage: functional-test
      script: bash ./ci/functional-test
    - stage: deploy
      script: bash ./ci/deploy
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        app: $HEROKU_APP_NAME
        api_key:
          secure: "$HEROKU_KEY"
        on:
          branches:
            - master
    - stage: smoke-test
      script: bash ./ci/smoke-test
 