language: node_js
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - node_modules
install: 
  - npm i -g npm@5.7.1
  - npm ci
stages:
  - name: functional-test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: functional-test
      script: npm start & (wait-on http://localhost:3000 && cypress run)
    - stage: deploy 
      script: ./ci/deploy
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        app: $HEROKU_APP_NAME
        api_key:
          secure: "$HEROKU_KEY"